/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "BasicTimer.h"
#include "GPIOxDriver.h"
#include "USARTxDriver.h"
#include <stdint.h>

GPIO_Handler_t handlerUserLed = {0};
GPIO_Handler_t handlerUserButton = {0};
BasicTimer_Handler_t handlerTIM2 = {0};

int main(void)
{
	handlerUserLed.pGPIOx =GPIOA;
	handlerUserLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	handlerUserLed.GPIO_PinConfig.GPIO_PinNumber = PIN_5;
	handlerUserLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OTYPE_PUSHPULL;
	handlerUserLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	handlerUserLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OSPEEDR_FAST;
	handlerUserLed.GPIO_PinConfig.GPIO_PinAltFunMode = AF0;

	GPIO_Config(&handlerUserLed);

	handlerTIM2.ptrTIMx = TIM2;
	handlerTIM2.TIMx_Config.TIMx_mode = BTIMER_MODE_UP;
	handlerTIM2.TIMx_Config.TIMx_speed = BTIMER_SPEED_10us;
	handlerTIM2.TIMx_Config.TIMx_period = 250;

	BasicTimer_Config(&handlerTIM2);

	while(1){
	TIM2_IRQHandler();
	}

}


void BasicTimer2_Callback(void){
	GPIOxTooglePin(&handlerUserLed);
}

