/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
/*
 * El paso por valor es una forma de definicion de funciones, donde las variables usadas
 * para que las funciones trabajen son copias de las variables originales, donde no se modifica el valor
 * de las ultimas.
 */
void duplicarNumero_PASO_POR_VALOR (uint8_t valor){
	valor*=2;
}
/*
 * El paso por referencia es una forma de definicion de funciones, donde las variables usadas
 * para que las funciones trabajen, son el propio espacio de almacenamiento, donde los cambios que haga
 * la funcion repercuten en la misma variable global
 */
void duplicarNumero_PASO_POR_REFERENCIA (uint8_t *valor){
	*valor = (*valor) * 2;
}

uint8_t duplicarNumero (uint8_t valor){
	return (valor *2);
}

void abonarDeudas (uint16_t deudas[] , uint8_t numeroDeDeudas){
	for (uint8_t i=0; i < numeroDeDeudas; i++){
		*(deudas+i) = (*(deudas+i)) / 2;

	}

}


//Actividad

void stringCaseConverter (uint8_t *string){

	uint8_t i = 0;

	while(string[i] != '\0'){
		if ((string[i] <= 122) && (string[i] >= 97)){
			string[i] -= 32;
		}else if ((string[i] <= 90) && (string[i] >= 65)){
			string[i] += 32;
		}else{
		}
		i++;
	}
}



int main(void)
{
	unsigned char n = 10;
	unsigned char m = 20;

	duplicarNumero_PASO_POR_VALOR(n);


	duplicarNumero_PASO_POR_REFERENCIA(&m);

	n = 12;
	m = 14;

	n = duplicarNumero(n);

	//STRINGS EN C

	uint8_t miPrimerString[]= "Hola Mundo";

	uint16_t deudasMensuales[5] = {1500,500,300,1000,2000};

	abonarDeudas(deudasMensuales, 5);

	//Crear una funcion llamada stringCaseCoverter que no retorne ningun valor
	//y recibe un string, cambiar las letras mayusculas por minusculas y viceversa

	uint8_t cambioDeLetras[] = "HoLa MunDO 11234 jhahskHHHSJ";

	stringCaseConverter(cambioDeLetras);

	n = 0;

	while(1){

	}






}
